name: Build GStreamer Full Library

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release tag'
        required: true
        default: '1.28.3'
      release_title:
        description: 'Release title'
        required: true
        default: 'GStreamer Full Library Build'

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout GStreamer source code
        uses: actions/checkout@v4
        with:
          repository: GStreamer/gstreamer
          path: gstreamer-source
          ref: '${{ inputs.release_tag }}'

      - name: Run build inside container
        id: build
        run: |

          mkdir -p /tmp/docker

          mv gstreamer-source /tmp/docker/

          cd /tmp/docker

          wget https://raw.githubusercontent.com/Waim908/rootfs-winlator/master/gstreamer.sh

          mv gstreamer.sh build_script.sh

          chmod +x /tmp/docker/build_script.sh


          # 运行容器
          docker run --rm \
            -v /tmp/docker:/workspace \
            waim908/ubuntuarm2404:wlt \
            /bin/bash -x /workspace/build_script.sh

      - name: Create Release and Upload Artifact
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.release_tag }}
          name: ${{ github.event.inputs.release_title }}
          files: /tmp/docker/gstreamer-full-${{ github.event.inputs.release_tag }}.tar.gz
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}